name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'   # 매일 자정 실행
  workflow_dispatch:      # 수동 실행 가능

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest blog posts (via rss2json)
        id: fetch_blog
        run: |
          curl -s "https://api.rss2json.com/v1/api.json?rss_url=https://nikihwangg.tistory.com/rss" > blog.json
          echo "Blog JSON saved"

      - name: Extract latest 5 posts
        id: extract_posts
        run: |
          POSTS=$(jq -r '.items[:5] | .[] | "- [\(.title)](\(.link)) <br> <small>\(.pubDate | sub("T";" ") | sub("\\+0900";""))</small>"' blog.json)
          echo "$POSTS" > posts.md
          echo "posts<<EOF" >> $GITHUB_OUTPUT
          cat posts.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update README with latest blog posts
        run: |
          START="<!-- BLOG_START -->"
          END="<!-- BLOG_END -->"
          POSTS="$(cat posts.md)"
          awk -v start="$START" -v end="$END" -v posts="$POSTS" '
            $0 ~ start {print; print posts; flag=1; next}
            $0 ~ end {flag=0}
            !flag {print}
          ' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit changes
        run: |
          git config user.name "d5ngjun2"
          git config user.email "nikihwangg@ivycomtech.com"
          git add README.md
          git commit -m "Update README with latest blog posts" || echo "No changes to commit"
          git push
