name: Update Blog Posts

on:
  schedule:
    - cron: '0 * * * *'  # 매시간
  workflow_dispatch:

permissions:
  contents: write   # ✅ 꼭 추가해야 함

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Pull in Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://nikihwangg.tistory.com/rss"
          max_post_count: 5
          readme_path: "./README.md"
