name: Update Blog Posts

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with RSS feed
        uses: matheusvanzan/rss-to-readme@v1
        with:
          feed: "https://nikihwangg.tistory.com/rss"
          readme: "./README.md"
          heading: "### 📝 Latest Blog Posts"
          max: 5
